- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure SSL VPN.
    fortios_vpn.ssl_settings:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      vpn.ssl_settings:
        state: "present"
        auth-timeout: "3"
        authentication-rule:
         -
            auth: "any"
            cipher: "any"
            client-cert: "enable"
            groups:
             -
                name: "default_name_9 (source: user.group.name)"
            id:  "10"
            portal: "<your_own_value> (source: vpn.ssl.web.portal.name)"
            realm: "<your_own_value> (source: vpn.ssl.web.realm.url-path)"
            source-address:
             -
                name: "default_name_14 (source: firewall.address.name firewall.addrgrp.name)"
            source-address-negate: "enable"
            source-address6:
             -
                name: "default_name_17 (source: firewall.address6.name firewall.addrgrp6.name)"
            source-address6-negate: "enable"
            source-interface:
             -
                name: "default_name_20 (source: system.interface.name system.zone.name)"
            users:
             -
                name: "default_name_22 (source: user.local.name)"
        auto-tunnel-static-route: "enable"
        banned-cipher: "RSA"
        check-referer: "enable"
        default-portal: "<your_own_value> (source: vpn.ssl.web.portal.name)"
        deflate-compression-level: "27"
        deflate-min-data-size: "28"
        dns-server1: "<your_own_value>"
        dns-server2: "<your_own_value>"
        dns-suffix: "<your_own_value>"
        dtls-hello-timeout: "32"
        dtls-tunnel: "enable"
        force-two-factor-auth: "enable"
        header-x-forwarded-for: "pass"
        http-compression: "enable"
        http-only-cookie: "enable"
        http-request-body-timeout: "38"
        http-request-header-timeout: "39"
        https-redirect: "enable"
        idle-timeout: "41"
        ipv6-dns-server1: "<your_own_value>"
        ipv6-dns-server2: "<your_own_value>"
        ipv6-wins-server1: "<your_own_value>"
        ipv6-wins-server2: "<your_own_value>"
        login-attempt-limit: "46"
        login-block-time: "47"
        login-timeout: "48"
        port: "49"
        port-precedence: "enable"
        reqclientcert: "enable"
        route-source-interface: "enable"
        servercert: "<your_own_value> (source: vpn.certificate.local.name)"
        source-address:
         -
            name: "default_name_55 (source: firewall.address.name firewall.addrgrp.name)"
        source-address-negate: "enable"
        source-address6:
         -
            name: "default_name_58 (source: firewall.address6.name firewall.addrgrp6.name)"
        source-address6-negate: "enable"
        source-interface:
         -
            name: "default_name_61 (source: system.interface.name system.zone.name)"
        ssl-client-renegotiation: "disable"
        ssl-insert-empty-fragment: "enable"
        tlsv1-0: "enable"
        tlsv1-1: "enable"
        tlsv1-2: "enable"
        tunnel-ip-pools:
         -
            name: "default_name_68 (source: firewall.address.name firewall.addrgrp.name)"
        tunnel-ipv6-pools:
         -
            name: "default_name_70 (source: firewall.address6.name firewall.addrgrp6.name)"
        unsafe-legacy-renegotiation: "enable"
        url-obscuration: "enable"
        wins-server1: "<your_own_value>"
        wins-server2: "<your_own_value>"
        x-content-type-options: "enable"
