- hosts: localhost
  vars:
   host: "192.168.122.40"
   username: "admin"
   password: ""
   vdom: "root"
  tasks:
  - name: Configure application control lists.
    fortios_application_list:
      host:  "{{  host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{  vdom }}"
      application_list:
        state: "present"
        app-replacemsg: "disable"
        comment: "comments"
        deep-app-inspection: "disable"
        entries:
         -
            action: "pass"
            application:
             -
                id:  "9"
            behavior: "<your_own_value>"
            category:
             -
                id:  "12"
            id:  "13"
            log: "disable"
            log-packet: "disable"
            parameters:
             -
                id:  "17"
                value: "<your_own_value>"
            per-ip-shaper: "<your_own_value> (source: firewall.shaper.per-ip-shaper.name)"
            popularity: "1"
            protocols: "<your_own_value>"
            quarantine: "none"
            quarantine-expiry: "<your_own_value>"
            quarantine-log: "disable"
            rate-count: "25"
            rate-duration: "26"
            rate-mode: "periodical"
            rate-track: "none"
            risk:
             -
                level: "30"
            session-ttl: "31"
            shaper: "<your_own_value> (source: firewall.shaper.traffic-shaper.name)"
            shaper-reverse: "<your_own_value> (source: firewall.shaper.traffic-shaper.name)"
            sub-category:
             -
                id:  "35"
            technology: "<your_own_value>"
            vendor: "<your_own_value>"
        extended-log: "enable"
        name: "default_name_39"
        options: "allow-dns"
        other-application-action: "pass"
        other-application-log: "disable"
        p2p-black-list: "skype"
        replacemsg-group: "<your_own_value> (source: system.replacemsg-group.name)"
        unknown-application-action: "pass"
        unknown-application-log: "disable"
